service: srvless-offline-node

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  simulate: yes

functions:
  hello:
    handler: handler.hello
    events:
      - http:
           path: /load
           method: GET
